name: Build and Publish image to Docker Hub

on:
  push:
    branches: ["master"]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Image
        run: |
          docker build ./api-services -t ${{ secrets.DOCKER_HUB_USERNAME }}/api-services:latest

      - name: Push Image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api-services:latest
